language: python

python:
  - "3.6" 

install:
  - sudo apt-get install pandoc ant ant-optional rpm alien
  - sudo apt-get install python3-pip python3-pyqt5
  - sudo pip3 install pyinstaller

after_success:
  - pyinstaller -F qt_demo.py

deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file:
      - dist/*
    on:
       repo: jacopotessera/qt_demo
    skip_cleanup: true
    on:
      tags: true
